### ISSUE TITLE
The website's JavaDoc link points to a page that does not exist

### ISSUE THREAD

**Issue by SaviorXTanren** [Radirius/Mercury#23]
The website's JavaDoc link has the following URL: http://htmlpreview.github.io/?https://raw.githubusercontent.com/Radirius/Mercury/stable/Project/out/site/apidocs/index.html

The "site" folder does not exist in the stable branch, but the folder does exist in the unstable branch. Either the link should be adjusted to point to the unstable branch (with version differences expected) or a new set of JavaDocs should be generated for the stable branch.

**Comment by sriharshachilakapati** [comment]
There are no javadocs in the repository of the stable branch, so that error. There are latest ones in the unstable branch, whose link should be this:

http://htmlpreview.github.io/?https://raw.githubusercontent.com/Radirius/Mercury/unstable/Project/out/site/apidocs/index.html

I'll fix the stable docs in a moment.

**Comment by sriharshachilakapati** [comment]
I have pushed the latest stable docs to the repo. This issue is now fixed.
